apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "minio-exporter.fullname" . }}
  labels:
    {{- include "minio-exporter.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "minio-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "minio-exporter.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "minio-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--minio.server={{ .Values.minioExporter.server }}"
            - "--web.listen-address={{ .Values.minioExporter.listenAddress }}"
            - "--web.telemetry-path={{ .Values.minioExporter.metricsPath }}"
            {{- if .Values.minioExporter.bucketStats }}
            - "--minio.bucket-stats"
            {{- end }}
          env:
            - name: MINIO_URL
              value: "{{ .Values.minioExporter.server }}"
            - name: LISTEN_ADDRESS
              value: "{{ .Values.minioExporter.listenAddress }}"
            - name: METRIC_PATH
              value: "{{ .Values.minioExporter.metricsPath }}"
            {{- if .Values.minioExporter.accessKey }}
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "minio-exporter.fullname" . }}-credentials
                  key: access-key
            {{- end }}
            {{- if .Values.minioExporter.accessSecret }}
            - name: MINIO_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "minio-exporter.fullname" . }}-credentials
                  key: access-secret
            {{- end }}
          ports:
            - name: http
              containerPort: 9290
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
